model:
  name: model_4
  parameters:
    embedding_dim: 128
    num_layers: 2

optimizer:
  lr: 1.0e-3

vocabulary:
  captions_file_path: "/Users/teapula/Documents/AIM/Deep_Learning/assignment_2/flickr8k/vocabulary_captions.txt"

data:
  train:
    images_folder_path: "/Users/teapula/Documents/AIM/Deep_Learning/assignment_2/flickr8k/train_images"
    captions_file_path: "/Users/teapula/Documents/AIM/Deep_Learning/assignment_2/flickr8k/train_captions.txt"
    batch_size: 256
  val:
    images_folder_path: "/Users/teapula/Documents/AIM/Deep_Learning/assignment_2/flickr8k/val_images"
    captions_file_path: "/Users/teapula/Documents/AIM/Deep_Learning/assignment_2/flickr8k/val_captions.txt"
    batch_size: 256
